from app.shared.settings.config import settings

from app.modules.rag.chunker_config import (  # noqa: F401  (re-export)
    CHUNKER_TARGET_TOKENS,
    CHUNKER_MAX_TOKENS,
    CHUNKER_MIN_TOKENS,
    CHUNKER_OVERLAP_TOKENS,
    CHUNKER_MAX_CHARS,
    RU_TJ_STOPWORDS,
    REASONING_MARKERS,
    TAJIK_TO_RU_HINTS,
)


DEFAULT_CHAT_MODEL = settings.OLLAMA_MODEL_CHAT
DEFAULT_EMBEDDING_MODEL = settings.OLLAMA_MODEL_EMBEDDING
MULTILINGUAL_EMBEDDING_MODEL = DEFAULT_EMBEDDING_MODEL
RELEVANCE_DISTANCE_THRESHOLD = 0.75
